# 全局配置
# 对于希望在同一时间使用多个配置文件的情况，例如两个GPU同时跑两个训练集：通过环境变量指定配置文件，不指定则默认为./config.yml

# 拟提供通用路径配置，统一存放数据，避免数据放得很乱
# 每个数据集与其对应的模型存放至统一路径下，后续所有的路径配置均为相对于datasetPath的路径
# 不填或者填空则路径为相对于项目根目录的路径
dataset_path: "Data/你的数据集文件夹"


# 预处理配置
data_pack:
  # 训练集文件 【没有必要就不要改默认值】
  train_filelist: "filelist/train.txt"
  # 训练集音频目录 【没有必要就不要改默认值】
  train_audios: "audios"
  # 预处理训练集数据输出目录 【没有必要就不要改默认值】
  train_datas: "datas/train"
  # 验证集文件 【没有必要就不要改默认值】
  eval_filelist: "filelist/eval.txt"
  # 验证集音频目录 【没有必要就不要改默认值】
  eval_audios: "audios"
  # 预处理验证集数据输出目录 【没有必要就不要改默认值】
  eval_datas: "datas/eval"
  # 处理并发数，根据电脑配置自己加，预处理吃显存
  num_process: 2
  # 是否在文本处理后的各种序列中添加空格（例如音素，音调等）（此处用于预处理，采用config.json中原始值）
  add_blank: true
  # config.json的模版文件，注意这个路径是相对于项目根的，其他都是相对于上面的dataset_path的
  config_in: "configs/config.json"
  # config.json预处理输出
  config_out: "config.json"

# Train 配置
train:
  # 相对于dataset_path下
  model_dir: models

# 多卡train 训练配置（暂时未适配多卡）
# 注意， “:” 后需要加空格
train_ms:
  # 需要加载的环境变量，多显卡训练时RANK请手动在环境变量填写
  # 环境变量对应名称环境变量不存在时加载，也就是说手动添加的环境变量优先级更高，会覆盖本配置文件
  env:
    MASTER_ADDR: "localhost"
    MASTER_PORT: 10086
    WORLD_SIZE: 1
    RANK: 0
    # 可以填写任意名的环境变量
    THE_ENV_VAR_YOU_NEED_TO_USE: "1234567"

# webui webui配置
# 注意， “:” 后需要加空格
webui:
  # 推理设备
  device: "cuda"
  # 模型路径
  model: "models/G_8000.pth"
  # 配置文件路径
  config_path: "config.json"
  # 端口号
  port: 7860
  # 是否公开部署，对外网开放
  share: false
  # 是否开启debug模式
  debug: false
  # 语种识别库，可选langid, fastlid
  language_identification_library: "langid"


# hiyori_UI 配置
# 注意， “:” 后需要加空格
# 注意，本配置下的所有配置均为相对于根目录的路径
hiyori_UI:
  # 端口号
  port: 5000
  # 模型默认使用设备：但是当前并没有实现这个配置。
  device: "cuda"
  # 需要加载的所有模型的配置
  # 注意，所有模型都必须正确配置model与config的路径，空路径会导致加载错误。
  models:
    - # 模型的路径
      model: ""
      # 模型config.json的路径
      config: ""
      # 模型使用设备，若填写则会覆盖默认配置
      device: "cuda"
      # 模型默认使用的语言
      language: "ZH"
      # 模型人物默认参数
      # 不必填写所有人物，不填的使用默认值
      # 暂时不用填写，当前尚未实现按人区分配置
      speakers: [ ]
    - # 模型的路径
      model: ""
      # 模型config.json的路径
      config: ""
      # 模型使用设备，若填写则会覆盖默认配置
      device: "cpu"
      # 模型默认使用的语言
      language: "JP"
      # 模型人物默认参数
      # 不必填写所有人物，不填的使用默认值
      speakers: [ ] # 也可以不填


# 百度翻译开放平台 api配置
# api接入文档 https://api.fanyi.baidu.com/doc/21
# 请不要在github等网站公开分享你的app id 与 key
translate:
  # 你的APPID
  "app_key": ""
  # 你的密钥
  "secret_key": ""
